# Generated by Django 4.1.2 on 2022-10-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('created_date', models.DateField(auto_now=True)),
                ('session_time', models.TimeField(blank=True, null=True, verbose_name='Время тренировки')),
                ('gym_name', models.CharField(choices=[('NB', 'Новая Боровая "Vibe"'), ('NEM', 'Немига "GymBox"')], default='Новая Боровая "Vibe', max_length=50, verbose_name='Зал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.profile', verbose_name='client_id')),
            ],
        ),
    ]
