# Generated by Django 4.1.2 on 2022-10-24 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('birthday_date', models.DateField(verbose_name='Дата рождения')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ник в Instagram')),
                ('telegram', models.CharField(max_length=50, null=True, verbose_name='Ник в Telegram')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('start_date', models.DateField(auto_now=True)),
                ('goal', models.CharField(choices=[('P', 'Физическая активность'), ('WL', 'Снижение веса'), ('MG', 'Набор мышечной массы')], default='Физическая активность', max_length=50, verbose_name='Цель')),
                ('gym_name', models.CharField(choices=[('NB', 'Новая Боровая "Vibe"'), ('NEM', 'Немига "GymBox"')], default='Новая Боровая "Vibe', max_length=50, verbose_name='Зал')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
