# Generated by Django 4.1.2 on 2022-12-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('P', 'Физическая активность'), ('WL', 'Снижение веса'), ('MG', 'Набор мышечной массы')], default='Физическая активность', max_length=50, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gym_name',
            field=models.CharField(choices=[('NB', 'Новая Боровая "Vibe"'), ('NEM', 'Немига "GymBox"')], default='Новая Боровая "Vibe', max_length=50, null=True, verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
