# Generated by Django 4.1.2 on 2022-12-12 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_alter_profile_birthday_date_alter_profile_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('P', 'Физическая активность'), ('WL', 'Снижение веса'), ('MG', 'Набор мышечной массы')], default='Физическая активность', max_length=50, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gym_name',
            field=models.CharField(blank=True, choices=[('NB', 'Новая Боровая "Vibe"'), ('NEM', 'Немига "GymBox"')], default='Новая Боровая "Vibe', max_length=50, null=True, verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
